name: spring-pet-clinic

on:
    push:
        branches:
            - 'feature/**'

permissions:
    checks: write

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Maven dependencies
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
            
            - name: Run maven package
              run: mvn clean package
            
            - name: Artifact upload
              uses: actions/upload-artifact@v4
              with:
                name: spc-artifact
                path: target/*.jar

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: |
                  **/surefire-reports/*.xml
              
            