name: spring-pet-clinic

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@4
            
            - name: Run maven package
              run: mvn package
            
            - name: Artifact upload
              uses: actions/upload-artifact@v4
              with:
                name: spc-artifact
                path: target/*.jar

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: |
                  **/surefire-reports/.xml
              
            